DROP TABLE IF EXISTS enums;
CREATE TABLE enums (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT enums_name_uindex UNIQUE (name)
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT users_username_uindex UNIQUE (username)
);

DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sid VARCHAR(255) NOT NULL, -- Session ID from cookie
  data VARCHAR(255) NOT NULL, -- JSON string
  CONSTRAINT sessions_sid_uindex UNIQUE (sid)
);

DROP TABLE IF EXISTS games;
CREATE TABLE games (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10) NOT NULL, -- Game code for invites
  status INT(6) UNSIGNED NOT NULL, -- Enum
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT games_code_uindex UNIQUE (code)
);

DROP TABLE IF EXISTS game_state;
CREATE TABLE game_state (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game INT(6) UNSIGNED NOT NULL,
  field INT(6) UNSIGNED NOT NULL, -- Enum
  value VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT gstate_value_uindex UNIQUE (game, field) -- Prevent duplicate states
);

DROP TABLE IF EXISTS players;
CREATE TABLE players (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user INT(6) UNSIGNED NOT NULL,
  game INT(6) UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT players_player_uindex UNIQUE (user, game) -- Prevent duplicate players
);

DROP TABLE IF EXISTS player_state;
CREATE TABLE player_state (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player INT(6) UNSIGNED NOT NULL,
  field INT(6) UNSIGNED NOT NULL, -- Enum
  value VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pstate_value_uindex UNIQUE (player, field) -- Prevent duplicate states
);

DROP FUNCTION IF EXISTS get_enum;
CREATE FUNCTION get_enum (name VARCHAR(255))
  RETURNS int(6) unsigned
  RETURN (SELECT id FROM enums WHERE enums.name = name);

SOURCE data.sql
